changelog:
  exclude:
    # A list of labels that exclude a pull request from appearing in release notes.
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes ğŸ› 
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features ğŸ‰
      labels:
        - Semver-Minor
        - feature
    - title: Other Changes
      labels:
        - '*'
  footer: |
    ### Revogrid:
    - â­ [Star the Revogrid Repo](https://github.com/revolist/revogrid)
    - ğŸ¦ [Follow at Twitter](https://x.com/revolist_ou/)
    - ğŸ”— [Follow at LinkedIn](https://www.linkedin.com/company/revolist)